/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'todayCheckOuts' : bigint,
  'todayCheckIns' : bigint,
  'totalGuests' : bigint,
  'totalRevenue' : number,
  'paymentMethodBreakdown' : PaymentBreakdown,
}
export interface ExportFilters {
  'dateTo' : [] | [string],
  'roomNumber' : [] | [string],
  'searchTerm' : [] | [string],
  'dateFrom' : [] | [string],
}
export interface Guest {
  'id' : GuestId,
  'isDeleted' : boolean,
  'paymentMethod' : PaymentMethod,
  'grcNumber' : string,
  'createdAt' : Time,
  'checkInDate' : string,
  'guestName' : string,
  'checkInTime' : string,
  'roomNumber' : string,
  'amountPaid' : number,
  'updatedAt' : Time,
  'invoiceNumber' : string,
  'address' : string,
  'notes' : string,
  'checkedIn' : boolean,
  'checkOutDate' : string,
  'idProofType' : string,
  'checkOutTime' : string,
  'phoneNumber' : string,
  'purposeOfVisit' : string,
  'roomType' : string,
  'idProofNumber' : string,
  'numberOfGuests' : bigint,
  'idProofImageUrl' : Array<string>,
}
export type GuestId = bigint;
export interface GuestInput {
  'paymentMethod' : PaymentMethod,
  'grcNumber' : string,
  'checkInDate' : string,
  'guestName' : string,
  'checkInTime' : string,
  'roomNumber' : string,
  'amountPaid' : number,
  'invoiceNumber' : string,
  'address' : string,
  'notes' : string,
  'checkOutDate' : string,
  'idProofType' : string,
  'checkOutTime' : string,
  'phoneNumber' : string,
  'purposeOfVisit' : string,
  'roomType' : string,
  'idProofNumber' : string,
  'numberOfGuests' : bigint,
  'idProofImageUrl' : Array<string>,
}
export interface GuestPage {
  'total' : bigint,
  'page' : bigint,
  'totalPages' : bigint,
  'guests' : Array<Guest>,
}
export interface PaymentBreakdown {
  'upi' : number,
  'other' : number,
  'card' : number,
  'cash' : number,
  'online' : number,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null } |
  { 'Online' : null } |
  { 'Other' : null };
export interface SearchParams {
  'page' : bigint,
  'includeDeleted' : boolean,
  'limit' : bigint,
  'toDate' : [] | [string],
  'searchTerm' : [] | [string],
  'fromDate' : [] | [string],
}
export type Time = bigint;
export interface _SERVICE {
  'addGuest' : ActorMethod<[GuestInput], Guest>,
  'deleteGuest' : ActorMethod<[GuestId], boolean>,
  'getAllGuestsForExport' : ActorMethod<[ExportFilters], Array<Guest>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getGuest' : ActorMethod<[GuestId], [] | [Guest]>,
  'getGuests' : ActorMethod<[SearchParams], GuestPage>,
  'hardDeleteGuest' : ActorMethod<[GuestId], boolean>,
  'restoreGuest' : ActorMethod<[GuestId], boolean>,
  'toggleGuestCheckIn' : ActorMethod<[GuestId], [] | [boolean]>,
  'updateGuest' : ActorMethod<[GuestId, GuestInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];