/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'Online' : IDL.Null,
  'Other' : IDL.Null,
});
export const GuestInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'grcNumber' : IDL.Text,
  'checkInDate' : IDL.Text,
  'guestName' : IDL.Text,
  'checkInTime' : IDL.Text,
  'roomNumber' : IDL.Text,
  'amountPaid' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutDate' : IDL.Text,
  'idProofType' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'purposeOfVisit' : IDL.Text,
  'roomType' : IDL.Text,
  'idProofNumber' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
  'idProofImageUrl' : IDL.Vec(IDL.Text),
});
export const GuestId = IDL.Nat;
export const Time = IDL.Int;
export const Guest = IDL.Record({
  'id' : GuestId,
  'isDeleted' : IDL.Bool,
  'paymentMethod' : PaymentMethod,
  'grcNumber' : IDL.Text,
  'createdAt' : Time,
  'checkInDate' : IDL.Text,
  'guestName' : IDL.Text,
  'checkInTime' : IDL.Text,
  'roomNumber' : IDL.Text,
  'amountPaid' : IDL.Float64,
  'updatedAt' : Time,
  'invoiceNumber' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'checkedIn' : IDL.Bool,
  'checkOutDate' : IDL.Text,
  'idProofType' : IDL.Text,
  'checkOutTime' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'purposeOfVisit' : IDL.Text,
  'roomType' : IDL.Text,
  'idProofNumber' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
  'idProofImageUrl' : IDL.Vec(IDL.Text),
});
export const ExportFilters = IDL.Record({
  'dateTo' : IDL.Opt(IDL.Text),
  'roomNumber' : IDL.Opt(IDL.Text),
  'searchTerm' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Opt(IDL.Text),
});
export const PaymentBreakdown = IDL.Record({
  'upi' : IDL.Float64,
  'other' : IDL.Float64,
  'card' : IDL.Float64,
  'cash' : IDL.Float64,
  'online' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'todayCheckOuts' : IDL.Nat,
  'todayCheckIns' : IDL.Nat,
  'totalGuests' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'paymentMethodBreakdown' : PaymentBreakdown,
});
export const SearchParams = IDL.Record({
  'page' : IDL.Nat,
  'includeDeleted' : IDL.Bool,
  'limit' : IDL.Nat,
  'toDate' : IDL.Opt(IDL.Text),
  'searchTerm' : IDL.Opt(IDL.Text),
  'fromDate' : IDL.Opt(IDL.Text),
});
export const GuestPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'totalPages' : IDL.Nat,
  'guests' : IDL.Vec(Guest),
});

export const idlService = IDL.Service({
  'addGuest' : IDL.Func([GuestInput], [Guest], []),
  'deleteGuest' : IDL.Func([GuestId], [IDL.Bool], []),
  'getAllGuestsForExport' : IDL.Func(
      [ExportFilters],
      [IDL.Vec(Guest)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getGuest' : IDL.Func([GuestId], [IDL.Opt(Guest)], ['query']),
  'getGuests' : IDL.Func([SearchParams], [GuestPage], ['query']),
  'hardDeleteGuest' : IDL.Func([GuestId], [IDL.Bool], []),
  'restoreGuest' : IDL.Func([GuestId], [IDL.Bool], []),
  'toggleGuestCheckIn' : IDL.Func([GuestId], [IDL.Opt(IDL.Bool)], []),
  'updateGuest' : IDL.Func([GuestId, GuestInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'Online' : IDL.Null,
    'Other' : IDL.Null,
  });
  const GuestInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'grcNumber' : IDL.Text,
    'checkInDate' : IDL.Text,
    'guestName' : IDL.Text,
    'checkInTime' : IDL.Text,
    'roomNumber' : IDL.Text,
    'amountPaid' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutDate' : IDL.Text,
    'idProofType' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'purposeOfVisit' : IDL.Text,
    'roomType' : IDL.Text,
    'idProofNumber' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
    'idProofImageUrl' : IDL.Vec(IDL.Text),
  });
  const GuestId = IDL.Nat;
  const Time = IDL.Int;
  const Guest = IDL.Record({
    'id' : GuestId,
    'isDeleted' : IDL.Bool,
    'paymentMethod' : PaymentMethod,
    'grcNumber' : IDL.Text,
    'createdAt' : Time,
    'checkInDate' : IDL.Text,
    'guestName' : IDL.Text,
    'checkInTime' : IDL.Text,
    'roomNumber' : IDL.Text,
    'amountPaid' : IDL.Float64,
    'updatedAt' : Time,
    'invoiceNumber' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'checkedIn' : IDL.Bool,
    'checkOutDate' : IDL.Text,
    'idProofType' : IDL.Text,
    'checkOutTime' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'purposeOfVisit' : IDL.Text,
    'roomType' : IDL.Text,
    'idProofNumber' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
    'idProofImageUrl' : IDL.Vec(IDL.Text),
  });
  const ExportFilters = IDL.Record({
    'dateTo' : IDL.Opt(IDL.Text),
    'roomNumber' : IDL.Opt(IDL.Text),
    'searchTerm' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Opt(IDL.Text),
  });
  const PaymentBreakdown = IDL.Record({
    'upi' : IDL.Float64,
    'other' : IDL.Float64,
    'card' : IDL.Float64,
    'cash' : IDL.Float64,
    'online' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'todayCheckOuts' : IDL.Nat,
    'todayCheckIns' : IDL.Nat,
    'totalGuests' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'paymentMethodBreakdown' : PaymentBreakdown,
  });
  const SearchParams = IDL.Record({
    'page' : IDL.Nat,
    'includeDeleted' : IDL.Bool,
    'limit' : IDL.Nat,
    'toDate' : IDL.Opt(IDL.Text),
    'searchTerm' : IDL.Opt(IDL.Text),
    'fromDate' : IDL.Opt(IDL.Text),
  });
  const GuestPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'totalPages' : IDL.Nat,
    'guests' : IDL.Vec(Guest),
  });
  
  return IDL.Service({
    'addGuest' : IDL.Func([GuestInput], [Guest], []),
    'deleteGuest' : IDL.Func([GuestId], [IDL.Bool], []),
    'getAllGuestsForExport' : IDL.Func(
        [ExportFilters],
        [IDL.Vec(Guest)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getGuest' : IDL.Func([GuestId], [IDL.Opt(Guest)], ['query']),
    'getGuests' : IDL.Func([SearchParams], [GuestPage], ['query']),
    'hardDeleteGuest' : IDL.Func([GuestId], [IDL.Bool], []),
    'restoreGuest' : IDL.Func([GuestId], [IDL.Bool], []),
    'toggleGuestCheckIn' : IDL.Func([GuestId], [IDL.Opt(IDL.Bool)], []),
    'updateGuest' : IDL.Func([GuestId, GuestInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };