/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Guest {
    id: GuestId;
    isDeleted: boolean;
    paymentMethod: PaymentMethod;
    grcNumber: string;
    createdAt: Time;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    updatedAt: Time;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkedIn: boolean;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
}
export interface PaymentBreakdown {
    upi: number;
    other: number;
    card: number;
    cash: number;
    online: number;
}
export type GuestId = bigint;
export interface GuestPage {
    total: bigint;
    page: bigint;
    totalPages: bigint;
    guests: Array<Guest>;
}
export interface SearchParams {
    page: bigint;
    includeDeleted: boolean;
    limit: bigint;
    toDate?: string;
    searchTerm?: string;
    fromDate?: string;
}
export interface GuestInput {
    paymentMethod: PaymentMethod;
    grcNumber: string;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
}
export interface ExportFilters {
    dateTo?: string;
    roomNumber?: string;
    searchTerm?: string;
    dateFrom?: string;
}
export interface DashboardStats {
    todayCheckOuts: bigint;
    todayCheckIns: bigint;
    totalGuests: bigint;
    totalRevenue: number;
    paymentMethodBreakdown: PaymentBreakdown;
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card",
    Cash = "Cash",
    Online = "Online",
    Other = "Other"
}
export interface backendInterface {
    addGuest(input: GuestInput): Promise<Guest>;
    deleteGuest(id: GuestId): Promise<boolean>;
    getAllGuestsForExport(filters: ExportFilters): Promise<Array<Guest>>;
    getDashboardStats(): Promise<DashboardStats>;
    getGuest(id: GuestId): Promise<Guest | null>;
    getGuests(params: SearchParams): Promise<GuestPage>;
    hardDeleteGuest(id: GuestId): Promise<boolean>;
    restoreGuest(id: GuestId): Promise<boolean>;
    toggleGuestCheckIn(id: GuestId): Promise<boolean | null>;
    updateGuest(id: GuestId, input: GuestInput): Promise<boolean>;
}
import type { ExportFilters as _ExportFilters, Guest as _Guest, GuestId as _GuestId, GuestInput as _GuestInput, GuestPage as _GuestPage, PaymentMethod as _PaymentMethod, SearchParams as _SearchParams, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGuest(arg0: GuestInput): Promise<Guest> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuest(to_candid_GuestInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Guest_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuest(to_candid_GuestInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Guest_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGuest(arg0: GuestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuest(arg0);
            return result;
        }
    }
    async getAllGuestsForExport(arg0: ExportFilters): Promise<Array<Guest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuestsForExport(to_candid_ExportFilters_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuestsForExport(to_candid_ExportFilters_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getGuest(arg0: GuestId): Promise<Guest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuest(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuest(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuests(arg0: SearchParams): Promise<GuestPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuests(to_candid_SearchParams_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GuestPage_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuests(to_candid_SearchParams_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GuestPage_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async hardDeleteGuest(arg0: GuestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hardDeleteGuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hardDeleteGuest(arg0);
            return result;
        }
    }
    async restoreGuest(arg0: GuestId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreGuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreGuest(arg0);
            return result;
        }
    }
    async toggleGuestCheckIn(arg0: GuestId): Promise<boolean | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleGuestCheckIn(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleGuestCheckIn(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGuest(arg0: GuestId, arg1: GuestInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuest(arg0, to_candid_GuestInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuest(arg0, to_candid_GuestInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_GuestPage_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuestPage): GuestPage {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Guest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Guest): Guest {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Guest]): Guest | null {
    return value.length === 0 ? null : from_candid_Guest_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    totalPages: bigint;
    guests: Array<_Guest>;
}): {
    total: bigint;
    page: bigint;
    totalPages: bigint;
    guests: Array<Guest>;
} {
    return {
        total: value.total,
        page: value.page,
        totalPages: value.totalPages,
        guests: from_candid_vec_n11(_uploadFile, _downloadFile, value.guests)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GuestId;
    isDeleted: boolean;
    paymentMethod: _PaymentMethod;
    grcNumber: string;
    createdAt: _Time;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    updatedAt: _Time;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkedIn: boolean;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
}): {
    id: GuestId;
    isDeleted: boolean;
    paymentMethod: PaymentMethod;
    grcNumber: string;
    createdAt: Time;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    updatedAt: Time;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkedIn: boolean;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
} {
    return {
        id: value.id,
        isDeleted: value.isDeleted,
        paymentMethod: from_candid_PaymentMethod_n7(_uploadFile, _downloadFile, value.paymentMethod),
        grcNumber: value.grcNumber,
        createdAt: value.createdAt,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        checkInTime: value.checkInTime,
        roomNumber: value.roomNumber,
        amountPaid: value.amountPaid,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        address: value.address,
        notes: value.notes,
        checkedIn: value.checkedIn,
        checkOutDate: value.checkOutDate,
        idProofType: value.idProofType,
        checkOutTime: value.checkOutTime,
        phoneNumber: value.phoneNumber,
        purposeOfVisit: value.purposeOfVisit,
        roomType: value.roomType,
        idProofNumber: value.idProofNumber,
        numberOfGuests: value.numberOfGuests,
        idProofImageUrl: value.idProofImageUrl
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Online: null;
} | {
    Other: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : "Cash" in value ? PaymentMethod.Cash : "Online" in value ? PaymentMethod.Online : "Other" in value ? PaymentMethod.Other : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Guest>): Array<Guest> {
    return value.map((x)=>from_candid_Guest_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ExportFilters_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportFilters): _ExportFilters {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_GuestInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestInput): _GuestInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SearchParams_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchParams): _SearchParams {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateTo?: string;
    roomNumber?: string;
    searchTerm?: string;
    dateFrom?: string;
}): {
    dateTo: [] | [string];
    roomNumber: [] | [string];
    searchTerm: [] | [string];
    dateFrom: [] | [string];
} {
    return {
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        roomNumber: value.roomNumber ? candid_some(value.roomNumber) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page: bigint;
    includeDeleted: boolean;
    limit: bigint;
    toDate?: string;
    searchTerm?: string;
    fromDate?: string;
}): {
    page: bigint;
    includeDeleted: boolean;
    limit: bigint;
    toDate: [] | [string];
    searchTerm: [] | [string];
    fromDate: [] | [string];
} {
    return {
        page: value.page,
        includeDeleted: value.includeDeleted,
        limit: value.limit,
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    grcNumber: string;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
}): {
    paymentMethod: _PaymentMethod;
    grcNumber: string;
    checkInDate: string;
    guestName: string;
    checkInTime: string;
    roomNumber: string;
    amountPaid: number;
    invoiceNumber: string;
    address: string;
    notes: string;
    checkOutDate: string;
    idProofType: string;
    checkOutTime: string;
    phoneNumber: string;
    purposeOfVisit: string;
    roomType: string;
    idProofNumber: string;
    numberOfGuests: bigint;
    idProofImageUrl: Array<string>;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n3(_uploadFile, _downloadFile, value.paymentMethod),
        grcNumber: value.grcNumber,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        checkInTime: value.checkInTime,
        roomNumber: value.roomNumber,
        amountPaid: value.amountPaid,
        invoiceNumber: value.invoiceNumber,
        address: value.address,
        notes: value.notes,
        checkOutDate: value.checkOutDate,
        idProofType: value.idProofType,
        checkOutTime: value.checkOutTime,
        phoneNumber: value.phoneNumber,
        purposeOfVisit: value.purposeOfVisit,
        roomType: value.roomType,
        idProofNumber: value.idProofNumber,
        numberOfGuests: value.numberOfGuests,
        idProofImageUrl: value.idProofImageUrl
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} | {
    Online: null;
} | {
    Other: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value == PaymentMethod.Online ? {
        Online: null
    } : value == PaymentMethod.Other ? {
        Other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
